FROM docker.elastic.co/kibana/kibana:7.11.0
RUN /usr/share/kibana/bin/kibana-plugin install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.11.2/enhanced-table-1.11.2_7.11.0.zip
RUN /usr/share/kibana/bin/kibana --optimize